export const data = {
  menu: {
    STARBUCKS: [
      {
        itemid: "A1",
        itemname: "Java Chip Frappuccino",
        itemprice: "315",
        outofstock: false,
      },
      {
        itemid: "A2",
        itemname: "Caramel Frappuccino",
        itemprice: "315",
        outofstock: true,
      },
      {
        itemid: "A3",
        itemname: "Double Chocolate Chip Frappuccino",
        itemprice: "345",
        outofstock: false,
      },
      {
        itemid: "A4",
        itemname: "Cappuccino",
        itemprice: "275",
        outofstock: true,
      },
      {
        itemid: "A5",
        itemname: "Caffe Mocha",
        itemprice: "280",
        outofstock: false,
      },
      {
        itemid: "A6",
        itemname: "Green Tea Latte",
        itemprice: "250",
        outofstock: false,
      },
      {
        itemid: "A7",
        itemname: "Chai Tea Latte",
        itemprice: "255",
        outofstock: false,
      },
      {
        itemid: "A8",
        itemname: "Java Chip With Chocolate Sauce And Chips",
        itemprice: "125",
        outofstock: true,
      },
      {
        itemid: "A9",
        itemname: "Caramel Macchiato With Salted Caramel Drizzle",
        itemprice: "125",
        outofstock: false,
      },
      {
        itemid: "A10",
        itemname: "Egg White And Chicken Ham In Multigrain Croissant",
        itemprice: "310",
        outofstock: false,
      },
      {
        itemid: "A11",
        itemname: "Butter Croissant With Butter",
        itemprice: "230",
        outofstock: false,
      },
      {
        itemid: "A12",
        itemname: "Almond Croissant",
        itemprice: "265",
        outofstock: true,
      },
      {
        itemid: "A13",
        itemname: "Tandoori Paneer Sandwich",
        itemprice: "310",
        outofstock: false,
      },
      {
        itemid: "A14",
        itemname: "Murgh Kathi Wrap",
        itemprice: "299",
        outofstock: false,
      },
      {
        itemid: "A15",
        itemname: "Chatpata Paratha Wrap",
        itemprice: "295",
        outofstock: false,
      },
      {
        itemid: "A16",
        itemname: "Chicken Naanwich",
        itemprice: "299",
        outofstock: false,
      },
      {
        itemid: "A17",
        itemname: "Chicken Seekh Pocket",
        itemprice: "199",
        outofstock: false,
      },
      {
        itemid: "A18",
        itemname: "New York Cheesecake",
        itemprice: "339",
        outofstock: true,
      },
    ],
    KFC: [
      {
        itemid: "B1",
        itemname: "5pc Leg Piece Bucket Meal",
        itemprice: "650",
        outofstock: true,
      },
      {
        itemid: "B2",
        itemname: "Friendship Bucket",
        itemprice: "734",
        outofstock: false,
      },
      {
        itemid: "B3",
        itemname: "Big 12",
        itemprice: "755",
        outofstock: true,
      },
      {
        itemid: "B4",
        itemname: "5pc Smoky Red Chicken",
        itemprice: "524",
        outofstock: true,
      },
      {
        itemid: "B5",
        itemname: "Classic Biryani Combo",
        itemprice: "777",
        outofstock: false,
      },
      {
        itemid: "B6",
        itemname: "Popcorn Chicken Biryani Bucket",
        itemprice: "241",
        outofstock: false,
      },
      {
        itemid: "B7",
        itemname: "All Chicken Box",
        itemprice: "199",
        outofstock: true,
      },
      {
        itemid: "B8",
        itemname: "Zinger Tandoori Box",
        itemprice: "329",
        outofstock: true,
      },
      {
        itemid: "B9",
        itemname: "2 Chicken Krisper Burgers",
        itemprice: "240",
        outofstock: false,
      },
      {
        itemid: "B10",
        itemname: "Mixed Zinger Doubles",
        itemprice: "366",
        outofstock: true,
      },
      {
        itemid: "B11",
        itemname: "Choco Mud Pie",
        itemprice: "135",
        outofstock: false,
      },
      {
        itemid: "B12",
        itemname: "Pepsi Black Can 330 ml",
        itemprice: "60",
        outofstock: false,
      },
      {
        itemid: "B13",
        itemname: "Mirinda Can 330 ml",
        itemprice: "60",
        outofstock: true,
      },
    ],

    BURGERKING: [
      {
        itemid: "C1",
        itemname: "Super Over Combo (Veg)",
        itemprice: "506",
        outofstock: true,
      },
      {
        itemid: "C2",
        itemname: "Super Over Combo (Chicken)",
        itemprice: "624",
        outofstock: false,
      },
      {
        itemid: "C3",
        itemname: "Strategic Timeout Combo (Chicken)",
        itemprice: "723",
        outofstock: false,
      },
      {
        itemid: "C4",
        itemname: "Crispy Veg Double Patty + Crispy Veg Double Patty",
        itemprice: "150",
        outofstock: true,
      },
      {
        itemid: "C5",
        itemname: "Crispy Chicken Double Patty ",
        itemprice: "238",
        outofstock: false,
      },
      {
        itemid: "C6",
        itemname: "Veg Whopper + Veg Whopper",
        itemprice: "338",
        outofstock: true,
      },
      {
        itemid: "C7",
        itemname: "2 Crispy Veg Double Patty + 1King Fries + 1Veggie strips",
        itemprice: "308",
        outofstock: false,
      },
      {
        itemid: "C8",
        itemname: "2 Lite Whopper Jr Veg + 1 King Fries + 1 Veggie strips",
        itemprice: "396",
        outofstock: false,
      },
      {
        itemid: "C9",
        itemname: "2 Crispy Chicken Double Patty 1 Chicken Fries",
        itemprice: "426",
        outofstock: true,
      },
      {
        itemid: "C10",
        itemname: "Hashbrown",
        itemprice: "39",
        outofstock: true,
      },
    ],
  },
};
